name: home
favicon: null
layout_spectrum: 0.5026162615977228
typography_spectrum: 0.6110459319315851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.23519021016545594
  lightness: 0.6368201663717628
  saturation: 0.9305191887542605
  rhythmicContrast: 0.5940260142087936
purpose: []
